apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h
  chart: 
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      version: ">=1.15.0-0"
  releaseName: "sealed-secrets-controller"
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    metrics:
      serviceMonitor:
        enabled: true
      dashboards:
        create: true
  