apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent
spec:
  selector:
    matchLabels:
      app: qbittorrent
  replicas: 1
  serviceName: "qbittorrent-utp"
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      nodeSelector:
        kubernetes.io/hostname: nagoya
      #securityContext:
      #  runAsUser: 1030
      #  runAsGroup: 65539
      #securityContext:
      #  sysctls:
      #    - name: fs.nr_open
      #      value: "2048"
      containers:
        - name: qbittorrent
          image: ghcr.io/linuxserver/qbittorrent:latest
          #image: alpine:edge
          #command: ["sh"]
          #stdin: true
          #tty: true
          #securityContext:
          #  allowPrivilegeEscalation: false
          #  runAsUser: 0
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
            name: web
          - containerPort: 6881
            protocol: TCP
            name: utptcp
          - containerPort: 6881
            protocol: UDP
            name: utpudp
          resources:
            requests:
              memory: "150Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "2"
          env:
          - name: TZ
            value: "UTC"
          - name: WEBUI_PORT
            value: "8080"
          - name: PUID
            value: "1030"
          - name: PGID
            value: "65539"
          volumeMounts:
          - name: config
            mountPath: /config
          - name: data-downloading
            mountPath: /downloads/downloading
          - name: data-complete
            mountPath: /downloads/complete
          - name: data-complete-deduplicate
            mountPath: /downloads/complete/deduplicate
          #livenessProbe:
          #  tcpSocket:
          #   port: utptcp
          #  initialDelaySeconds: 20
          #  periodSeconds: 30
          # - name: configmap
          #  mountPath: /config/.rtorrent.rc
          #  readOnly: true
          #  subPath: rtorrent.rc
          # livenessProbe:
          #   tcpSocket:
          #    port: xmlrpc
          #  initialDelaySeconds: 20
          #  periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vault-downloads-duck-torrents
      - name: data-downloading
        persistentVolumeClaim:
          claimName: vault-downloads-duck-torrents-downloading
      - name: data-complete
        persistentVolumeClaim:
          claimName: vault-downloads-duck-torrents-complete
      - name: data-complete-deduplicate
        persistentVolumeClaim:
          claimName: vault-downloads-duck-torrents-complete-deduplicate
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: manual
      resources:
        requests:
          storage: 10Mi
      volumeName: qbittorrent-config
  