apiVersion: apps/v1
kind: Deployment
metadata:
  name: owntracks-recorder
  labels:
    app: owntracks-recorder
spec:
  selector:
    matchLabels:
      app: owntracks-recorder
  template:
    metadata:
      labels:
        app: owntracks-recorder
    spec:
      containers:
      - image: owntracks/recorder:latest
        name: recorder
        resources:
          requests:
            memory: "100Mi"
            cpu: "150m"
          limits:
            memory: "200Mi"
            cpu: "300m"
        env:
        - name: OTR_STORAGEDIR
          value: "/store"
        #- name: OTR_CAFILE
        #  value: "/etc/ssl/certs/ca-cert-DST_Root_CA_X3.pem"
        - name: OTR_HOST
          value: "mosquitto.ln-database.svc.cluster.local"
        - name: OTR_HTTPPREFIX
          value: "https://recorder.owntracks.theleachfamily.me.uk"
        - name: OTR_PORT
          value: "1883"
        - name: OTR_USER
          value: "owntracks"
        - name: OTR_PASS
          value: "cb2ed57fe2c19abe4dea40a7a653206d715f6e381a558749"
        - name: OTR_PRECISION
          value: "7"
        - name: OTR_GEOKEY
          value: "cb2ed57fe2c19abe4dea40a7a653206d715f6e381a558749"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          timeoutSeconds: 1
          failureThreshold: 30
        ports:
        - containerPort: 8083
          name: http
        volumeMounts:
        - name: data
          mountPath: /store
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: owntracks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: owntracks-frontend
  labels:
    app: owntracks-frontend
spec:
  selector:
    matchLabels:
      app: owntracks-frontend
  template:
    metadata:
      labels:
        app: owntracks-frontend
    spec:
      containers:
      - image: owntracks/frontend:latest
        name: frontend
        resources:
          requests:
            memory: "25Mi"
            cpu: "50m"
          limits:
            memory: "30Mi"
            cpu: "75m"
        env:
        - name: SERVER_HOST
          value: "owntracks-recorder.ln-owntracks.svc.cluster.local"
        - name: SERVER_PORT
          value: "8083"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 30
          timeoutSeconds: 1
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: config
          mountPath: usr/share/nginx/html/config/config.js
          subPath: config.js
      volumes:
        - name: config
          configMap:
            name: owntracks-frontend-config