apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ln-owntracks

resources:
- deployment.yaml
- pvc.yaml
- ingress.yaml
- service.yaml

configMapGenerator:
- name: owntracks-frontend-config
  namespace: ln-owntracks
  files:
  - config.js