apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argo-cd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Infrastructure elements, such as databases.
  destinations:
  - name: ducknet
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceNamespaces:
  - '*'
  sourceRepos:
  - '*'