apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: identity-system
spec:
  chart:
    spec:
      chart: authelia
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
      version: '*'
  interval: 10m0s
  values:
    configMap:
      authentication_backend:
        file:
          enabled: false
        ldap:
          additional_groups_dn: OU=lists
          additional_users_dn: OU=users
          base_dn: DC=duck,DC=moe
          display_name_attribute: cn
          enabled: true
          group_name_attribute: cn
          groups_filter: (&(uniquemember={dn})(objectclass=groupOfUniqueNames))
          mail_attribute: mail
          url: ldap://openldap.identity-system.svc
          user: CN=authelia,OU=applications,DC=duck,DC=moe
          username_attribute: uid
          users_filter: (&({username_attribute}={input})(objectClass=inetOrgPerson))
      default_redirection_url: https://duck.moe
      enabled: true
      identity_providers:
        oidc:
          clients:
          - authorization_policy: one_factor
            description: Matrix - Synapse
            id: matrix_synapse
            public: false
            redirect_uris:
            - https://matrix.duck.moe/_synapse/client/oidc/callback
            scopes:
            - openid
            - profile
            - email
            secret: a1d8509966c70ecb5ff292ca58b88a9f083f820b3a293d179ca5e186128909a8ca9a72aa1b279f28bd6949eda9e79723d68f3f0857ebaca1b2a44e865b7d0ab7
            userinfo_signing_algorithm: none
          - authorization_policy: two_factor
            description: Kubernetes on ducknet.
            id: kubernetes
            public: true
            redirect_uris:
            - http://localhost:8000
            - http://localhost:18000
            scopes:
            - openid
            - profile
            - groups
            secret: ""
          - authorization_policy: two_factor
            description: files.duck.
            id: nextcloud
            public: false
            redirect_uris:
            - https://files.duck.moe/apps/user_oidc/code
            scopes:
            - openid
            - profile
            - groups
            - email
            secret: 3sSZaXNWOyYwmNCDrZwQKRuH6gnEwBO0
            userinfo_signing_algorithm: none
          enabled: true
      notifier:
        filesystem:
          enabled: true
        smtp:
          enabled: false
      session:
        file:
          enabled: false
        name: ducknet_session
        redis:
          enabled: true
          enabledSecret: true
          host: redis-master.database.svc
      storage:
        local:
          enabled: false
        mysql:
          enabled: false
        postgres:
          database: authelia
          enabled: true
          host: postgresql.database.svc
          username: authelia
      telemetry:
        enabled: true
        serviceMonitor:
          enabled: true
      totp:
        disable: false
        issuer: ducknet.
      webauthn:
        disable: false
        display_name: ducknet.
    domain: duck.moe
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http-prod
      enabled: true
      subdomain: auth.id
      tls:
        secret: authelia-cert
      traefikCRD:
        disableIngressRoute: true
        enabled: true
    rbac:
      enabled: true
    secret:
      existingSecret: authelia
      jwt:
        filename: JWT_TOKEN
        key: JWT_TOKEN
        value: ""
      ldap:
        filename: LDAP_PASSWORD
        key: LDAP_PASSWORD
        value: ""
      oidcHMACSecret:
        filename: OIDC_HMAC_SECRET
        key: OIDC_HMAC_SECRET
        value: ""
      oidcPrivateKey:
        filename: OIDC_PRIVATE_KEY
        key: OIDC_PRIVATE_KEY
        value: ""
      redis:
        filename: REDIS_PASSWORD
        key: REDIS_PASSWORD
        value: ""
      session:
        filename: SESSION_ENCRYPTION_KEY
        key: SESSION_ENCRYPTION_KEY
        value: ""
      storage:
        filename: STORAGE_PASSWORD
        key: STORAGE_PASSWORD
        value: ""
      storageEncryptionKey:
        filename: STORAGE_ENCRYPTION_KEY
        key: STORAGE_ENCRYPTION_KEY
        value: ""