apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: ln-data
spec:
  selector:
    matchLabels:
      app: paperless
  replicas: 1
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
        - name: paperless
          image: jonaswinkler/paperless-ng:latest
          ports:
          - containerPort: 8000
            protocol: TCP
            name: http
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "200Mi"
              cpu: "1"
          env:
          - name: PAPERLESS_REDIS
            value: "redis://paperless-redis.ln-data.svc.cluster.local:6379"
          - name: PAPERLESS_DBHOST
            value: "postgresql.ln-database.svc.cluster.local"
          - name: PAPERLESS_DBUSER
            valueFrom:
              secretKeyRef:
                name: paperless
                key: postgresDbUser
          - name: PAPERLESS_DBPASS
            valueFrom:
              secretKeyRef:
                name: paperless
                key: postgresDbPassword
          - name: PAPERLESS_TIKA_ENABLED
            value: "1"
          - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
            value: "http://paperless-tika.ln-data.svc.cluster.local:3000"
          - name: PAPERLESS_TIKA_ENDPOINT
            value: "http://paperless-tika.ln-data.svc.cluster.local:9998"
          - name: PAPERLESS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: paperless
                key: secretKey
          - name: PAPERLESS_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: paperless
                key: adminUser
          - name: PAPERLESS_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: paperless
                key: adminPassword
          - name: PAPERLESS_ENABLE_HTTP_REMOTE_USER
            value: "true"
          - name: PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME
            value: "HTTP_X_AUTHENTIK_USERNAME"
          volumeMounts:
          - name: data
            mountPath: /usr/src/paperless/data
            subPath: "data"
          - name: data
            mountPath: /usr/src/paperless/media
            subPath: "media"
          - name: export
            mountPath: /usr/src/paperless/export
          - name: consume
            mountPath: /usr/src/paperless/consume
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: paperless-data
      - name: export
        emptyDir: 
      - name: consume
        emptyDir: 