apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-cam-proxy
  namespace: ln-home
spec:
  selector:
    matchLabels:
      app: unifi-cam-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: unifi-cam-proxy
    spec:
      containers:
        - name: cam-proxy
          image: koehler/unifi-cam-proxy:protect-124
          command: ["unifi-cam-proxy", "--host", "10.0.0.253", "--cert", "/client.pem", "--token", "gJuhoXtCRtlLrJcZTpaAo62YiljPAAvf", "rtsp", "-s", "rtsp://unifi:0o9HfA5oxkCH@10.0.0.210:554/stream0"]
          # resources:
          #  requests:
          #    memory: "50Mi"
          #    cpu: "10m"
          #  limits:
          #    memory: "1Gi"
          #    cpu: "2"
          volumeMounts:
          - name: certificate
            mountPath: /client.pem
            subPath: client.pem
      volumes:
      - name: certificate
        secret:
          secretName: unifi-protect-camera-certificate
