apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mosquitto-ingress
spec:
  entryPoints:
    - mqtts
  routes:
  - match: HostSNI(`*`)
    services:
    - name: mosquitto
      port: 8883
  tls:
    domains:
    - main: "mqtt.net.theleachfamily.me.uk"
    secretName: mosquitto-cert
    passthrough: true