apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ln-database

resources:
- deployment.yaml
- pvc.yaml
- ingress.yaml
- service.yaml
- certificate.yaml
- secret.yaml

configMapGenerator:
- name: mosquitto-config
  namespace: ln-database
  files:
  - config/mosquitto.conf
