apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- configmap.yaml
- service.yaml
- ingress.yaml
# - servicemonitor.yaml
- pvc.yaml

namespace: ducknet-devops
