apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-registry
  namespace: default
spec:
  encryptedData:
    HTPASSWD: AgCaK32tj+LCdzYrSpsSEdRo7So28+mzkXSQlQgajjmZzTJP7oq2VR0MECwanwhXWBfqZAHK+YsHLYT3McQ7r+UEX7ken0/ApB5HIjy3dBkvFawbC87x59JNzwPc9yA38Dp7A5yC8VvAd0wE9FnC7gZjCI5n085bpJ7mhHb8KNemOmW0pqIjNLV6iUyY4xbd9Y3NOU/vsg3tHhaC2gNuNbUuu5YvA64kTs7A2h0igdGlcYsDmz/FjDOXa+bwQz5jiIcB4oEm1HNI87jBOBMmjHi4sy6W2ZE1WRZ3nwo8Xh5w55y8zB+xr+Tf98maQ9lUuVycqWIwAiOdStjFDQnQrG/Qn3J58z4uDWukAGSebnPXr2HbQg/ZAZ6rGKtz2RR1VTjBvrItAXZIMQEVIbMyVfS6YHQGnwJXFRiOfc0hHL05WXy9E1fCD7Gsg6yjtLt0mT1kpnTdzXYpPrx4Sv1cGtLvDl7HNySEyzxpZySoHSOJT4VBUdA3xb6d99eFdVR/xRZQN7MTxI4VhwCpTws8vSxuZnJ0LuZFlCmpNuV2ChqZHZ7EhUmnI7S1INv0eN+QGAsEZh4laMQT3hQHk8YfGJRjRLUe1O9tnzGWS3e/Jm53ygf9M1Q/B8FEHUOtM+YX5BPfIg+89hPLFnwwHK7NaAHtEkTM9pzRHpb645yZDR1afHtLOvPZOCYj8UpFIKlgtmlUFeA6ZhOAuRsCxtL6WPRK5ED0IDJSgBkfQqzN2gxa21VE1VsQXsSlC4gn7OWsgKw/ljJYSN0oJDh1d5npfvhCE/LMkbv6LxJp2e4eOeqm7WgnffRgKXAVHCye5z1stiLedv9sdAhfplWAyjCUd+bZO4Lpz8G3X4LTMQlKoJefzoRZOLp7O+LdqFWg1fHAYMpeYago8moZhgsc1IaPb8K1Z6LqSew+6585HwSD2kxKoxpq5r0Ii8+wVC59CCitD85sPYpqC0AaJXBcxKkaiWzZY7v2bhsuzPkK4rCswCYkpXY0NCpRQcLz83OL9FQK7EurYUph16Qy3KmBc23M6wPcDfT2VkFHOJyz276SgeBk/ByfBspNnV+4tgLgk9tpdLtlkSG137Y6z76ec0b1Pg31IyFKpDQ0Y/74NTc0rTldp1gES29gzSLW95y1urwzzi/G69C6BREHiRSxe9kv
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: docker-registry
      namespace: default
    type: Opaque

