apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  selector:
    app: docker-registry
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
  - name: debug
    protocol: TCP
    port: 5001
    targetPort: 5001
