apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: docker-registry
  name: docker-registry
spec:
  endpoints:
  - interval: 60s
    port: debug
    scheme: http
  namespaceSelector:
    matchNames:
    - ci
  selector:
    matchLabels:
      app: docker-registry



