apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http-staging
spec:
  acme:
    email: cert-admin@partyparrot.moe
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-key
    solvers:
    - http01:
        ingress:
          class: traefik
          serviceType: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http-prod
spec:
  acme:
    email: cert-admin@partyparrot.moe
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: prod-key
    solvers:
    - http01:
        ingress:
          class: traefik
          serviceType: ClusterIP
