apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vpn
  namespace: argo-cd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Elements providing a Virtual Private Network for personal use.
  destinations:
  - name: ducknet
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceNamespaces:
  - 'vpn'
  sourceRepos:
  - '*'