apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rrc
  namespace: argo-cd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Elements providing resources for the Ringwood Repair Café.
  destinations:
  - name: ducknet
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceNamespaces:
  - 'rrc'
  sourceRepos:
  - '*'