apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik-remote
  namespace: identity-system
spec:
  interval: 1m0s
  chart: 
    spec:
      chart: authentik-remote-cluster
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
  values:
    