apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: dn-games
spec:
  interval: 1m0s
  chart: 
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  values:
    livenessProbe:
      failureThreshold: 60
    readinessProbe:
      failureThreshold: 60
    startupProbe:
      enabled: true
      failureThreshold: 120
      periodSeconds: 10
    minecraftServer:
      eula: "TRUE"
      type: "VANILLA"
      maxPlayers: 24
      maxWorldSize: 10000
      ops: 'duckfullstop'
      gameMode: "creative"
      motd: "The Allie Pallie (with love from duck. ❤)"
      pvp: true
      # resourcePackEnforce: true
      serviceType: NodePort
      nodePort: 25565
      overrideServerProperties: true
    persistence:
      dataDir:
        enabled: True
        existingClaim: "minecraft-data"
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
        