---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1h
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/duckfullstop/infra
  ignore: |
    # exclude all
    /*
    # except the k8s manifests
    !/k8s
    # although there are a few other things we don't need
    /k8s/**/*.txt
    /k8s/**/*.md
