apiVersion: apps/v1
kind: Deployment
metadata:
  name: tronity-sync
  namespace: ln-automotive
spec:
  selector:
    matchLabels:
      app: tronity
  replicas: 1
  template:
    metadata:
      labels:
        app: tronity
    spec:
      containers:
        - name: sync
          image: tronity/sync:latest
          ports:
          - containerPort: 8080
            protocol: TCP
            name: http
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "500m"
