apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: irc-edefnet-cert
  namespace: ducknet
spec:
  dnsNames:
    - edef.bouncer.irc.duck.moe
  secretName: irc-edefnet-cert
  issuerRef:
    name: letsencrypt-http-prod
    kind: ClusterIssuer