apiVersion: apps/v1
kind: Deployment
metadata:
  name: pounce-edefnet
spec:
  selector:
    matchLabels:
      app: pounce-edefnet
  replicas: 1
  template:
    metadata:
      labels:
        app: pounce-edefnet
    spec:
      containers:
        - name: pounce
          image: ghcr.io/duckfullstop/cri-pounce:latest
          command: ['pounce', '-v', '/config/pounce.conf']
          resources:
            requests:
              memory: "20Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
          - name: config
            mountPath: /config
          - name: certs
            mountPath: /config/certs
            readOnly: true
          - name: cli-cert
            mountPath: /config/certs-cli
            readOnly: true
          ports:
          - containerPort: 6697
            protocol: TCP
            name: irc-ssl
      volumes:
        - name: config
          configMap:
            name: pounce-edefnet
        - name: certs
          secret:
            secretName: irc-edefnet-cert
        - name: cli-cert
          secret:
            secretName: irc-edefnet-cli-cert