apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- deployment.yaml
- secret-plain.yaml
- service.yaml
- ingress.yaml

namespace: ducknet

# TODO NOCOMMIT secrets in config
configMapGenerator:
- name: pounce-edefnet
  namespace: ducknet
  files:
  - config/pounce.conf