apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- deployment.yaml
- secret.yaml
- service.yaml
- ingress.yaml

namespace: ducknet

configMapGenerator:
- name: pounce-edefnet
  namespace: ducknet
  files:
  - config/pounce.conf