apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtl433
  namespace: ln-home
spec:
  selector:
    matchLabels:
      app: rtl433
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rtl433
    spec:
      initContainers:
      - name: init-wait-for-mqtt
        image: busybox
        command: ['sh', '-c', 'until nc -zv mosquitto.ln-database.svc 1883; do echo waiting for mosquitto; sleep 2; done;']
      containers:
        - name: rtl433
          image: ghcr.io/hertzg/rtl_433_docker:latest
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
              duck.moe/radio-433mhz: "1"
            limits:
              memory: "200Mi"
              cpu: "100m"
              duck.moe/radio-433mhz: "1"
          securityContext:
            privileged: true
            procMount: Default
          volumeMounts:
          - name: config
            mountPath: /etc/rtl_433/rtl_433.conf
            readOnly: true
            subPath: rtl_433.conf
          # Selection is performed in a finer fashion (serial number) by the config.
          - name: dev-bus-usb
            mountPath: /dev/bus/usb
          - name: secrets
            mountPath: /etc/rtl_433/secret.conf
            readOnly: true
            subPath: secret.conf
      volumes:
      - name: config
        configMap:
          name: rtl433-config
          optional: false
      - name: dev-bus-usb
        hostPath:
          path: /dev/bus/usb
          type: Directory
      - name: secrets
        secret:
          secretName: rtl433
          optional: false