apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ln-home

resources:
- deployment.yaml
- secret.yaml

configMapGenerator:
- name: rtl433-config
  namespace: ln-home
  files:
  - config/rtl_433.conf