apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 1m0s
  chart: 
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  values:
    deployment:
      enabled: true
      kind: DaemonSet
    experimental:
      http3:
        enabled: false
    ingressRoute:
      dashboard:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-http-prod
          traefik.ingress.kubernetes.io/router.middlewares: identity-system-authentik-forward-auth@kubernetescrd
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
    ports:
      web:
        port: 80
        expose: true
        exposedPort: 80
        nodePort: 80
        redirectTo: websecure
      websecure:
        expose: true
        exposedPort: 443
        port: 443
        nodePort: 443
        http3: false
        tls:
          enabled: true
      traefik:
        expose: true
      mqtts:
        port: 8883
        expose: true
        exposedPort: 8883
        nodePort: 8883
        protocol: TCP
      ldaps:
        port: 636
        expose: true
        exposedPort: 636
        nodePort: 636
        protocol: TCP
    service:
      enabled: true
      externalTrafficPolicy: Local
      ipFamilies:
      - IPv4
      - IPv6
      ipFamilyPolicy: PreferDualStack
      type: NodePort
    securityContext:
      capabilities:
        drop: [ALL]
        add: [NET_BIND_SERVICE]
      readOnlyRootFilesystem: true
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0