apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-core
  namespace: argo-cd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Infrastructure elements, such as ingress controllers and CNI.
  destinations:
  - name: ducknet
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceNamespaces:
  - argo-cd
  - kube-flannel
  - kube-system
  sourceRepos:
  - '*'