apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/persist/service/vaultwarden"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nagoya
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: vaultwarden-pv
