apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persist/service/mosquitto"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
