apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex-tls
  namespace: identity-system
spec:
  secretName: dex-tls
  issuerRef:
    kind: ClusterIssuer
    name: local-ca
  dnsNames:
  - dex
  - dex.identity-system
  - dex.identity-system.svc.cluster.local
