apiVersion: apps/v1
kind: Deployment
metadata:
  name: antennas
  namespace: ln-media
spec:
  selector:
    matchLabels:
      app: antennas
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: antennas
    spec:
      containers:
        - name: antennas
          image: thejf/antennas:4.1.0
          resources:
            requests:
              memory: "75Mi"
              cpu: "5m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - name: http
              containerPort: 5004
          env:
            - name: ANTENNAS_URL
              value: "http://tvheadend.ln-media.svc.cluster.local:5004"
            - name: TVHEADEND_URL
              valueFrom:
                secretKeyRef:
                  name: antennas
                  key: tvhUrl
                  optional: false
            - name: TUNER_COUNT
              value: "4"
          startupProbe:
            httpGet:
              path: /discover.json
              port: http
            failureThreshold: 12
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /discover.json
              port: http
            timeoutSeconds: 60
          livenessProbe:
            httpGet:
              path: /discover.json
              port: http
            timeoutSeconds: 60

