apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: identity-system
commonLabels:
  app: dex

resources:
- certificate.yaml
- configmap.yaml
- deployment.yaml
- ingress.yaml
- rbac.yaml
# - secret.yaml
- service.yaml
