# A service account so Dex can connect to the Kubernetes API to store session management data.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dex
  namespace: identity-system
---
# An RBAC role for use with the above service account.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dex
rules:
# Read-write access to all of Dex's custom objects, used for session management.
- apiGroups: [dex.coreos.com] # API group created by dex
  resources: ["*"]
  verbs: ["*"]
# Access to install the CRDs for Dex's custom objects.
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  verbs: [create]
---
# Bind the service account and the RBAC role together.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dex
subjects:
- kind: ServiceAccount
  name: dex
  namespace: identity-system
