apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  serviceName: "mariadb"
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      nodeSelector:
        kubernetes.io/hostname: kumamoto
      containers:
        - name: mariadb
          image: mariadb:10
          args: [ "--innodb_log_group_home_dir=/var/lib/mysql/innodb_logs", "--skip-innodb-doublewrite", "--innodb_use_native_aio=0", "--innodb_use_atomic_writes=0" ]
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3306
            protocol: TCP
            name: sql
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
          - name: innodb-logs
            mountPath: /var/lib/mysql/innodb_logs
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: manual
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: innodb-logs
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: manual
      resources:
        requests:
          storage: 1Gi