apiVersion: v1
kind: PersistentVolume
metadata:
  name: esphome-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persist/service/esphome"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome
  namespace: ln-home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
