apiVersion: apps/v1
kind: Deployment
metadata:
  name: adsbexchange
  namespace: ln-ads
spec:
  selector:
    matchLabels:
      app: adsbexchange
  replicas: 1
  template:
    metadata:
      labels:
        app: adsbexchange
    spec:
      containers:
        - name: adsbexchange
          image: mikenye/adsbexchange:latest
          tty: true
          ports:
          - containerPort: 8754
            protocol: TCP
            name: http
          - containerPort: 30105
            protocol: TCP
            name: mlat
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "250Mi"
              cpu: "500m"
          env:
          - name: BEASTHOST
            value: "readsb"
          - name: BEASTPORT
            value: "30005"
          - name: TZ
            value: "Europe/London"
          - name: UUID
            valueFrom:
              secretKeyRef:
                name: ads-b
                key: ADSBEXCHANGE_UUID
          - name: LAT
            valueFrom:
              secretKeyRef:
                name: ads-b
                key: SITE_LATITUDE
          - name: LONG
            valueFrom:
              secretKeyRef:
                name: ads-b
                key: SITE_LONGITUDE
          - name: ALT
            valueFrom:
              secretKeyRef:
                name: ads-b
                key: SITE_LATITUDE
          - name: SITENAME
            valueFrom:
              secretKeyRef:
                name: ads-b
                key: SITE_NAME
          #livenessProbe:
          #  exec:
          #    command:
          #      - /scripts/healthcheck.sh
          #  initialDelaySeconds: 3600
          #  periodSeconds: 60
          volumeMounts:
          - name: run
            mountPath: /dev/bus/usb
      volumes:
      - name: run
        emptyDir: {}