apiVersion: apps/v1
kind: Deployment
metadata:
  name: tar1090
  namespace: ln-ads
spec:
  selector:
    matchLabels:
      app: tar1090
  replicas: 0 # Not currently working, segfaults at readsb/api.c#1713 :(
  template:
    metadata:
      labels:
        app: tar1090
    spec:
      containers:
        - name: tar1090
          image: ghcr.io/sdr-enthusiasts/docker-tar1090:latest
          ports:
          - containerPort: 80
            protocol: TCP
            name: http
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "750Mi"
              cpu: "500m"
          env:
          - name: BEASTHOST
            value: "readsb"
          - name: BEASTPORT
            value: "30005"
          - name: TZ
            value: "Europe/London"
          - name: LAT
            valueFrom:
              secretKeyRef:
                name: ads-b
                key: SITE_LATITUDE
          - name: LONG
            valueFrom:
              secretKeyRef:
                name: ads-b
                key: SITE_LONGITUDE
          - name: MLATHOST
            value: "adsbexchange"
          - name: MLATPORT
            value: "30105"
          - name: READSB_EXTRA_ARGS
            value: "--devel=apiThreads,1"
          livenessProbe:
            exec:
              command:
                - /scripts/healthcheck.sh
            periodSeconds: 60
            failureThreshold: 3
            timeoutSeconds: 30
          startupProbe:
            exec:
              command:
                - /scripts/healthcheck.sh
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 30
          volumeMounts:
            - name: run
              mountPath: /run
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: run
          emptyDir:
            medium: "Memory"
            sizeLimit: 64M
        - name: varlog
          emptyDir: {}