apiVersion: v1
kind: PersistentVolume
metadata:
  name: readsb-autogain
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persist/service/readsb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readsb-autogain
  namespace: ln-ads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
