apiVersion: v1
kind: PersistentVolume
metadata:
  name: tvheadend-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/persist/service/tvheadend"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nagoya