apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: auth-system
spec:
  selector:
    matchLabels:
      app: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:latest
          args: ["--loglevel", "debug"]
          stdin: true
          tty: true
          ports:
          - containerPort: 389
            protocol: TCP
            name: ldap
          resources:
            requests:
              memory: "50Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          env:
          - name: LDAP_ORGANISATION
            value: "leachnet"
          - name: LDAP_DOMAIN
            value: "theleachfamily.me.uk"
          - name: LDAP_TLS
            value: "false"
          #- name: HOSTNAME
          #  value: "ldap-server"
          - name: KEEP_EXISTING_CONFIG
            value: "true"
          volumeMounts:
          - name: config
            mountPath: /etc/ldap/slapd.d
          - name: db
            mountPath: /var/lib/ldap
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: openldap-config
      - name: db
        persistentVolumeClaim:
          claimName: openldap-db
