apiVersion: v1
kind: PersistentVolume
metadata:
  name: openldap-db
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persist/service/openldap/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-db
  namespace: identity-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openldap-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persist/service/openldap/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-config
  namespace: identity-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
  storageClassName: manual
