apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: identity-system
commonLabels:
  app: traefik-forward-auth

resources:
- certificate.yaml
- deployment.yaml
- ingress.yaml
- middleware.yaml
- secret.yaml
- service.yaml

configMapGenerator:
- name: config
  files:
    - config/traefik-forward-auth.ini
