apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notify-matrix-token
  namespace: flux-system
spec:
  encryptedData:
    address: AgAb75j54X5QMlFGb3MCAX6cwkP8YhnNqo4lrMVB3BUZB9z3oUXkOhn5V26Cbf26O4NkurRwsxhhwFvWGuhIPXp5lEpOS7MovXDxNjoU9Uz3NG+NBgBhVygvEBZEpqhMZCFrnU7VzpSahamTJQekpj6MckoGKyd1Bu5ZMi3TCiJYFd/U7yOavKuh/Sjtm7Gx4LXE58siKNXc8KP5C4WmbiwLwYiRVr6it+dhUbV+fvtIIeUJpVu39uFUJfSbPXyEOwJru/AJblGRD9CO7xj8R516RQA/sK/JW5CF1jBSAM+WQRJfFXgvfdaLV4KE9hjEWLhZtljVXwY7MQZWnnnOEUjf6dQPVV1Uof5wEYUiL8/hGJJIUFWIQaOqN8BRFMBNqs+ggcDVIYpRk6oMvCebC3E+U5F6HsOkaMxY6kCkuq9WH9lNwjhdQfpKpn5clQhNlOhCknGk9xF+0dTZWint9HBJr57nti3Ph1VdlL2o0rGpeu4aaJnRHVaYDZ6MAlZ2Ge2Yxw2QW4qs3XYyQtZICdctcAhZQVPBUOqCiBMNacAip3AGmx8v5lA3pu+rwvBYgDUQeT247j7rgKP3hovoz7FBu7s/e9T5YD8X+OS0dJDK4c9wPI4ogBIU7tEOFTgZkxvgUVRyYJUsq1skjGGpV1FZM7aYXeWOmrfw0bx8oNicXZJDgj5cXMeQKRKW7TCIcHDl/QB9fsEyztYvoF8nSFpaXFRRKMI0kg==
    token: AgDTovpbzZjnWzabjHx89jU/wrUgr1yodwTgOrACsJ0F+cBbsHGjzQEwcOB53QUxtOzMZKKCIWy7UPbwWrGgBTo4eD3kP0Cgyy93/1BymaoWe/NbVeUqFqIYBrN8GPNCsTD8vHN58x+t4PQk10E8rJIaW7YZKGNNLNhEYKXQNeu+7X0GWz++d/1htcRF0tYV6ZT75LEpcCo8s0Su/mh0lVuHGz8w/qVyNo3YIgGFzJsVUUngsOcPoQ7U0UVB/d8mOdhTH/OBiLmxZMAyConZo4n4kq7RdU0cQ1o1/mHLF3k0VRXJGQlqzCJn6Y/UldXGiVSjNZjIyUhOtMKe11ddDmqFdLNyRFa/6PnVhLZP4NApFCQaUeFrInnQizn8tcWwed0rIJijuQd33mZLpA6JdOWFBm6uCRcAtPNNPNzFm/ksOO8CW9mZK1IXJx+DJOkd5DQHY8U+WchbvJdiHZWHnUx+pXqll2hkuer1X6l5BM/HA2672qKBqQbstvhFBG8pet9NJLOHnVclsbrmou+OTOWnJBPBDOGM+0zfue7GLLCcioN7uPUISuvf3KRlPGdLgwVkyIGMuukXYvqHweWRH+jFAayaDeJzn6949B83kwu9tyMBVkWbuM7HzwmIOBM32yBcrFh/zlTT2RvQX85U8+jsD0VOMXzTSOrV7vG+dx4lSVnTtDvC3wVC0jU52fzG7yPvw3VR2fsitJ6efhPbMQgVozb5T+S+IzhwpvJcup8uOnWSWunk3tc1kZh5
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: notify-matrix-token
      namespace: flux-system
    type: Opaque

