apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ldap
  namespace: identity-system
spec:
  encryptedData:
    adminPassword: AgAjxPH5a8h4MjaPeNXBupJu7R1LTXcIQy3ESxqqdngVtSFG41fuQ/3MT086im5qjxgTjfMzq7Z5Pu6BAD38nRUgVW0wsAQxnk2FfBlmUEDsR+ViqMXLNrShlihwLHB93vz3Z1yb+2HXXPHSefOvt78UjgbC3BURTrtLzy47WRplEffZcSa12B2wSc5ldPcIzxS6RhVEGJ/9iqh2Z+/pdLYkzA/qqzcJ8Yxzk7o7kKgqeN30T0z6CeUImJ0dp/hLpJWqgDjz55Sqml1V5IdyQpxrf/u4XWCMNtSE4DUFLqbLj7a3567aCD3x0omFDsW5hoaLlDzmOnTc4OBfVK0qRs9+xaMtZHYYvcrQT2+qL7Qke2FJjexYLP33pMokPvh3jluD887y960TQteuhN7s8OHny/oBaw0LLNQ7kvuR/s68JOB9B9OF1iMGu94fuldGo8//FrzM8u5DXKRD5J4lMty+mQjZv8S4bjDwqrx6tDBD7xQ5VTkI/61mAoN/ZRoh4iq1D8jzcavD8/BOQfH6h1nEiDrhQdLbmB0UdkIIXdwV+TJ5imV3ibYzISz7EzpNQVeBPOJxxFKFu7VW3SzfyOqcSdxKUgI3TbtE0klVJtN2SWx1KZRyQ9YNlIUGnlIQCj89fXsdI5iSU+6Q3AL83M0WomwrNh8wV+XdnzOPJ8FaSb/OmeKLfMUYmnGMxcRXrJ2h8DKpgrB4ZEP8lxE=
    configPassword: AgAuEHF7bVebei3g+sWtgmRd8X0cIAiI/friAsL+DXmL51x96er2L9TFvrg5wcUErpbW6yCrdxKW/U/Wr0Q09u9kKQ4cRF+zu9Z6ElGd9G8BRGc6egUsM5gieSvJTnWtTolSYCMuKWICQHQVUJNNLfqA0CEVXn27KSPDhOV6XeMkBIH8cj1C9jR4MehSZYHRMR2nyujnPIyzUgZ8p9B7LXWyGCdnlGcdxubYHqCybHcpB0/h4P2hIMl5QQSeb2MzDSsoSoW/XaNTztlFWaIyqsb0bOdKQ/rLeRn6VVc936cG9fKHB3n42Wi0+ijwWuEYegxJ7UyvPwgwPAZWr/RzolPzA1fj2FJEEpJO3FJU54JPYtX6X0YHT05x2M5RJCMIWmwf8v+DUphM6ayfGA3oJ2gb5dRMl/OWmfq1bS9OW6g7/iQbZyk7xW4lGn2cB3oIiVBSCaM6zj88JhaljxaVqh6KS4lQtRZy9vdQdGmLYPttYKDt2H9GUv0U19ps6JuLBC+C5+YCoiO+O3RkginJxoRwNEgdTRwF+dxSzU8M8yZ4vMIvoECuzej7a+TJrTD+wVzuN5kGcvJPihkzP+Y3grg9jbEmyVQmhaAbb3GyOqYkPVoCOhycUinC/Bizsd+UQp7/072oQ4a36Bf0YCbajMd6+00595LyAt7TJpndEOf4gvC5T9G7UA/QgDBIJoUUiZdHoOwejI+Jep6UfgI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ldap
      namespace: identity-system
    type: Opaque

