apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ln-home

resources:
- statefulset.yaml
- service.yaml
- ingress.yaml
- secret.yaml
- pv.yaml

configMapGenerator:
- name: zigbee2mqtt-config
  namespace: ln-home
  files:
  - config/configuration.yaml
- name: custom-converter
  namespace: ln-home
  files:
  - config/HIVELDSSIREN001.js