apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/persist/service/zigbee2mqtt"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nagoya