apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: identity
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hcloud-volumes
