apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: identity-system
spec:
  interval: 1m0s
  chart: 
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: authentik-config
      valuesKey: secretKey
      targetPath: authentik.secret_key
      optional: false
    - kind: Secret
      name: authentik-config
      valuesKey: redisPassword
      targetPath: authentik.redis.password
      optional: false
  values:
    authentik:
      error_reporting:
        enabled: true
      postgresql:
        host: "postgresql.database.svc.cluster.local"
        user: file:///authentik-secrets/postgresDbUser
        password: file:///authentik-secrets/postgresDbPassword
        name: file:///authentik-secrets/postgresDbName
      redis:
        host: "redis-master.database.svc.cluster.local"
    global:
      image:
        tag: "2024.6"
      volumes:
        - name: authentik-config
          secret:
            secretName: authentik-config
        - name: media
          persistentVolumeClaim:
            claimName: authentik-media
      volumeMounts:
        - name: authentik-config
          mountPath: /authentik-secrets
          readOnly: true
        - name: media
          mountPath: /media
    server:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-http-prod"
        hosts:
          - auth.duck.moe
          - auth.theleachfamily.me.uk
        tls:
          - hosts:
              - auth.duck.moe
              - auth.theleachfamily.me.uk
            secretName: "authentik-cert"
      
        