apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: identity-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
