apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 48h
  chart: 
    spec:
      chart: coredns
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
  values:
    prometheus:
      service:
        enabled: true
      monitor:
        enabled: true
    service:
      clusterIP: fc00:abc0::254