apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-downloads-duck
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  local:
    path: "/mnt/vault/downloads/duck/transmission/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nagoya
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-media-pvr
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  local:
    path: "/mnt/vault/media/pvr"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nagoya
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/persist/service/plex"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nagoya