apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-downloads-duck
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: "manual"
  volumeName: "plex-downloads-duck"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-pvr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: "manual"
  volumeName: "plex-media-pvr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
