apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-downloads-duck-torrents-complete
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: "manual"
  volumeName: "ln-media-vault-downloads-duck-torrents-complete"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-pvr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: "manual"
  volumeName: "vault-media-pvr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
