apiVersion: v1
kind: PersistentVolume
metadata:
  name: tvheadend-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persist/service/tvheadend"
