apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: ln-database
spec:
  interval: 1m0s
  chart: 
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    persistence:
      existingClaim: "postgres-data"
    metrics:
      enabled: true
#      serviceMonitor:
#        enabled: true
    postgresqlDatabase: "default"
    fullnameOverride: "postgresql"