apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 1m0s
  chart: 
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  values:
    deployment:
      enabled: true
      kind: DaemonSet
    experimental:
      kubernetesGateway:
        # enabled: true
        enabled: false
      http3:
        enabled: false
    ingressRoute:
      dashboard:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: identity-system-ak-outpost-ducknet-proxy-outpost@kubernetescrd
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
    ports:
      web:
        port: 80
        expose: true
        exposedPort: 80
        nodePort: 80
        redirectTo: websecure
      websecure:
        expose: true
        exposedPort: 443
        port: 443
        nodePort: 443
        http3: false
        tls:
          enabled: true
      traefik:
        expose: true
      mqtts:
        port: 8883
        expose: true
        exposedPort: 8883
        nodePort: 8883
        protocol: TCP
      ldaps:
        port: 636
        expose: true
        exposedPort: 636
        nodePort: 636
        protocol: TCP
      ircs:
        port: 6697
        expose: true
        exposedPort: 6699
        nodePort: 6699
        protocol: TCP
    service:
      enabled: true
      spec:
        externalTrafficPolicy: Local
      ipFamilies:
      - IPv4
      - IPv6
      ipFamilyPolicy: PreferDualStack
      type: NodePort
    securityContext:
      capabilities:
        drop: [ALL]
        add: [NET_BIND_SERVICE]
      readOnlyRootFilesystem: true
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    # tracing:
    additionalArguments:
      - "--tracing.jaeger=true"
      - "--tracing.serviceName=traefik"
      - "--tracing.jaeger.localAgentHostPort=jaeger-agent.ducknet-devops.svc.cluster.local:6831"
      - "--tracing.jaeger.gen128Bit=false"
      - "--tracing.jaeger.samplingType=const"
      - "--tracing.jaeger.samplingParam=1"
      - "--tracing.jaeger.traceContextHeaderName=x-b3-traceid"
      - "--tracing.jaeger.propagation=b3"