apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- crd.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- service-account.yaml
- daemonset.yaml
- service.yaml
- https-redirect.yaml
- ingress.yaml

commonLabels:
  app: traefik
