apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: root
  namespace: argo-cd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: App of apps.
  destinations:
  - name: ducknet
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'