apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flood
  namespace: dn-downloads
spec:
  encryptedData:
    qb_password: AgAeucdYZrM9z/NhG75kYIjxeTDSfhImfOf25vJ2eccMlrb3LxjD1huo8k9rBFD0Dc972FrtJXtJDCC2ZIUxE/F7MvGABx01/Nz2rYwALf7Ymq+uL7G4/v2Z5RnuTdIGtdDXGwR2GkSDi6XJnhAmLA6Gu0m25bo6WwwOMTIAt3mW+WmmvVyfKjvSNGS/Y+WnX/yE+MphBRSR8dfxj7/EaHhYif9Y9F5oj9P1tYr5QKPjLqzL7xb/7KXLmzW7m25YX3KuFob4KF0XVHBC6yDWbFrr5Oqtlx/JQjBbiwS5T62li/V6JbRODeUWhal8OvFH7MZJmA5wR7TrzRJUiXqCOZgs4FtL54XEhUvVlrSQwyoD0uIX85b3pZ9BOKCtxgPS8YTgVjo6Orh4JZ/Ty3NHkoPu0Wet/TrUNJY81u8kLkxkY8Y4SqTCwsDurTcehfhAAl+A/KK/P9tDlYATJhZCKlXINxNXCBpCrHWueoFf1lcEYyeJUs5K+87yIw/ebjsxrtAi5612Blvqz2qNms6CMvdyWlGCjxqynFsVJMeq7nKA7/+xGmOrOjpgCjRM63kFBUbERATL6fLBTyg0ZmwmzTh81pMcdCBtj+AzPr/Z2oDSAy1dI+MgkfHJ7j9ebDmsPNqNjZgiFgqTECtz0CofwuKx83Sn8A/MRweHEvHLQPZmm3ALoYbv/xZOXSdK3w+KTjaFiMGjfwOiwUyk
    qb_username: AgA5febjAjytpEIBrD31sFnwg8iZcrj0At14srrgKxMWhd+FFq/wlH/H3sSoNMnWPhOsKsQ9h2PHFKYsMdYFaAsMVX2KQD9hqxS6+eE0TV2ck1++JeqKqVuO2KxsfBiGQOYNUECAt1WSruODdQUTJz0Z/vTl0C3UHijHE+EvVE2YZGlmzNhrIH6XNn4r2RsgIU9V1DjQVPcBjZ9/tBY+J2PIRXIuY8bDzdEY14o4C698v2ypNPBqFVgOZ49VWnNhlG6VNlh7nW4dS4663m5k06pBkivErB4y9GiCb6tobNPdxxmX0XGc35HHMBrWyoux9mtZw9vPdThPoYpQ+YROTFHB9aXEsCe4Nefw1h4AdV8VZARCEq68bRTYVOZMwPy1ZK/z3QXyMmILO9iIjKb0s3ZcH7iFhuFsMReew4qrXnb4ZF4CpNtzK34wPc9xHu3WSmlJJ4J1FzUoVkEEo03NZID8a2Mex0bSvtcxC6ayDQ+i8arSvmeYeVpAT+prdLW9nageFrenNfgkRuKM8KTJRX45Wjanq1Df0F5nhUyDu32oq9XAY0vHhNJEftiZsPs+G0do6Sl43FLquhnGpnBiMra54nrM7k60xVbfTBKzZehwHh0m3FVf1bxJFgmcZeSFPz/q2tkNwqn8Br2Z8T5A8aD0RPez1hgTgshV44rwLOgoh6bfP3Bp/MQ844Mz8c9FvQyVd6yBlw==
  template:
    metadata:
      creationTimestamp: null
      name: flood
      namespace: dn-downloads
    type: Opaque

