apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ln-home

resources:
- ingress.yaml
- pv.yaml
- statefulset.yaml
- service.yaml

configMapGenerator:
- name: homebridge-config
  namespace: ln-home
  files:
  - config/package.json
