apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: synapse
  namespace: ducknet
spec:
  interval: 1m0s
  chart: 
    spec:
      chart: matrix-synapse
      sourceRef:
        kind: HelmRepository
        name: ananace-charts
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: matrix-synapse
      # This is really dumb. Injects the entirety of extraSecrets.oidc_providers[0]
      valuesKey: oidcProvider.yaml
      optional: false
    - kind: Secret
      name: matrix-synapse
      valuesKey: postgresDbName
      targetPath: externalPostgresql.database
    - kind: Secret
      name: matrix-synapse
      valuesKey: postgresDbUser
      targetPath: externalPostgresql.username
    - kind: Secret
      name: matrix-synapse
      valuesKey: postgresDbPassword
      targetPath: externalPostgresql.password
      optional: false
    - kind: Secret
      name: matrix-synapse
      valuesKey: redisPassword
      targetPath: redis.auth.password
      optional: false
    # I have literally no idea why the chart requires this to be defined in two places
    # but it does so here we are
    - kind: Secret
      name: matrix-synapse
      valuesKey: redisPassword
      targetPath: externalRedis.password
  values:
    serverName: duck.moe
    publicServerName: matrix.duck.moe
    synapse:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 128Mi
    workers:
      resources:
        limits:
          cpu: 150m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
    wellknown:
      enabled: true
      useIpv6: true
      resources:
        limits:
          cpu: 5m
          memory: 15Mi
        requests:
          cpu: 5m
          memory: 15Mi
    extraConfig:
      suppress_key_server_warning: true
      password_config:
        enabled: false
    postgresql:
      enabled: false
    externalPostgresql:
      host: "postgresql.database.svc.cluster.local"
    redis:
      enabled: false
    externalRedis:
      host: "redis-master.database.svc.cluster.local"
    persistence:
      enabled: true
      existingClaim: "synapse-data"
    ingress:
      enabled: true
      tls:
        - hosts:
            - matrix.duck.moe
          secretName: "matrix-cert"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-http-prod"
      