apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-data
  namespace: ducknet
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path