apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  project: infra
  sources:
    - repoURL: 'https://charts.jetstack.io'
      targetRevision: v1.16.x
      helm:
        valuesObject:
          installCRDs: true
          prometheus:
            enabled: false
            servicemonitor:
              enabled: false
      chart: cert-manager
    - repoURL: 'https://github.com/duckfullstop/infra-ln/'
      path: k8s/infra/cert-manager/manifests
      targetRevision: main
  destination:
    namespace: cert-manager
    name: ducknet