# This certificate instantiation is necessary because we don't have a standard Ingress for cert-manager to watch out for.
# Instead, manually request the certificate here, and then bind it to our IngressRouteTCP.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openldap-cert
  namespace: identity-system
spec:
  dnsNames:
    - ldap.id.duck.moe
  secretName: openldap-cert
  issuerRef:
    name: letsencrypt-http-prod
    kind: ClusterIssuer
