apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin
  namespace: identity-system
spec:
  selector:
    matchLabels:
      app: phpldapadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      containers:
        - name: openldap
          image: osixia/phpldapadmin:latest
          ports:
          - containerPort: 80
            protocol: TCP
            name: http
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "250m"
          env:
          - name: PHPLDAPADMIN_LDAP_HOSTS
            value: "openldap.identity-system.svc"
            # value: "#PYTHON2BASH:[{'openldap.identity-system.svc': [{'server': [{'tls': False},{'port': 389}]},{'login': [{'bind_id': 'cn=admin,dc=example,dc=org'}]}]}]"
          - name: PHPLDAPADMIN_HTTPS
            value: "false"
