apiVersion: v1
kind: ConfigMap
metadata:
  name: rtorrent
data:
  rtorrent.rc: |
    ## Import default config
    import = /etc/rtorrent/rtorrent.rc

    network.max_open_files=512
    network.max_open_sockets.set=10

    ## Listen to uTP on these ports
    network.port_range.set = 51401-51402

    ## Run process as a daemon
    system.daemon.set = true
