apiVersion: v1
kind: PersistentVolume
metadata:
  name: rtorrent-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/persist/service/rtorrent"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nagoya
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-downloads-duck-torrents
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  local:
    path: "/mnt/vault/downloads/duck/torrents"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nagoya
