apiVersion: v1
kind: Service
metadata:
  name: rtorrent-rpc
spec:
  ports:
  - name: xmlrpc
    port: 9099
    targetPort: xmlrpc
  selector:
    app: rtorrent
---
apiVersion: v1
kind: Service
metadata:
  name: rtorrent-utp
spec:
  ports:
  - name: utptcp
    port: 51401
    nodePort: 51401
    protocol: TCP
    targetPort: utptcp
  - name: utpudp
    port: 51401
    nodePort: 51401
    protocol: UDP
    targetPort: utpudp
  selector:
    app: rtorrent
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
   - IPv4
   - IPv6
  type: NodePort