apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: itzg
  namespace: flux-system
spec:
  interval: 24h
  url: https://itzg.github.io/minecraft-server-charts/
  timeout: 5m
