apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ananace.yaml
- bitnami.yaml
- goauthentik.yaml
- kubernetes-dashboard.yaml
- k8s-at-home.yaml
- prometheus-community.yaml
- sealed-secrets.yaml
- traefik.yaml