apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 6h
  url: https://bitnami-labs.github.io/sealed-secrets
  timeout: 3m