apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: ln-database
spec:
  interval: 1m0s
  chart: 
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    architecture: "standalone"
    master:
      persistence:
        existingClaim: "redis-data"
    replica:
      replicaCount: 0
    # metrics:
    #  enabled: true
#      serviceMonitor:
#        enabled: true
    fullnameOverride: "redis"
    # auth:
    #   existingSecret: "redis"