---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pocketid
  namespace: identity
spec:
  encryptedData:
    dbConnectionString: AgAzxf2YjI/PYCwdUWzR8adsxILHGr0+7QW78XIRKfEYni3f4056PRWewEQxLJ08zHQHDmq2wjPAL2G6+owb35i1EZhhmfD7r/oPTcIiph1ebvfWkxLBXst9bRL5W2FqI2Mk08to0ciJL4KbyaIOYKB3kpj7xaj0b/M5cHA3AeqGPLdbanjGy2mn2j/kw0V6OzS8oMztE0FyaZmkOflYCTTYTPL0gHyVhMLZwHx8kDEgC7mXSBn6OuOudjxdt8YGb5LaJU1yIdXh3iIcRTVz+iHaE7hPXLK8T6K+ITCT5gaCgHw7Es7169AoS3WRR4gTjRmbvtfItSrK09iathr0PI7uJJUPNQuXSUcFYEwLG9Wd8LkMnSgWzALKGVW8GD5yTOGibUbpf/GYRNvJ50MFNO+3N+F5qGBRNFRELf2nqZuu5MvgSXvmLbCh+haGcSEZiBrgXy9AvVseKsohdo6hD0bbRr9w67fcDeo+FxWV9YnrbLzehyJvwgjgKARfW1EcclbxQTgy6PfojEXo5Rs6nPrUZPGsii0OVo+rJPTP5gsfnkNWLY4QLr7M28hHchqLzWlmWAlEw8PH/jRqZG27xPEyx1ItD+NEuC1T7SmS3/7dizdBzYyzpkrp6bX/mgpHzJitxRZQD/NuWxwUnZrkTgWos1MMNK5M6eUYoj7Cb3pRHAY6kCtPaRdN4zd4ozAbJYXikhRh1TRGh3JObva5ySN79WQjMDD117jcuIVu9AxYcZYBtpotLw2IgWxRIq4KEJNC+UDkINRnSBlnDbJ565NSWH+9Od80NVdwKQ4i1d3QOXeA2+pzljPMDMqfMGZCs2mqXIaqz9RxVQ==
    encryptionKey: AgBzCiUTA/9DpC2h+6zqaT7msqfN6Ac7teGCV69pw6lH0EOJ6u9QFVf88iVVTiWhU188sBc9+w7pWFFjDdZfhBfZp5T94FQH/7GijA9J9bQxDKc8NqgTfvmipJ5WAehp3fdlJZelHH8eBmiwKer4irAdYqSgY4IX0YEvkZatP+t5dRzQpTdJ/C//jf6QzaqNqlFSR2sWETPmTLvrDfROz2SGimwzvr2xqGrMAVHYBo9WRXPn9G9m3jnKit/FBbHJnkk0OoeDGUNght1P3u6DqoQgXgIflIPuvPaU2AFE4BfMs2/yRggwVaEhZK7g0xN6yFoBnxf523h+1aMOVm71izoLQdkSZ6j45bz/bMbYCCs2rVeRFCjUuw8VZPeeCQBaD6AJQpX2X3ACAdXxKT00I66r/7FkeH+6RLoxCORywOk3zGmGGyYhZGrvBFNcuTJO+1l/98Ct9hSNItzB0lvFG4RY1h1obl87QrDtbKda2pJQkom9LOdC6eAqYjPKcZjPsqEITUOerwQ9JQlmBG9aouq9igTDp0kAL/duM8oDjxNdggRek3y0Y20F+nJBbdZmOi5whsBn28kOkTqOxJXNG019Xfrn7Nm7XJSN2dqcqkOHqjdJXqSANe4LalZjIz3ebeUyfk8klkTe9Baqs5NatpMTd1tVllaiRgX0SLlJ3hHSzNfuiNiT9P1wC+qucLRw9b1qxFfo3AJ7PznLCbsDT/ZtkTao2JknvTAcHG/XmcEmOsCvitRtJVbz57f2Bw==
  template:
    metadata:
      creationTimestamp: null
      name: pocketid
      namespace: identity
    type: Opaque
