apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: ln-database
spec:
  interval: 1m0s
  chart: 
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    # persistence.storageClass: "longhorn-fast"
    persistence.existingClaim: "postgres-data"
    # persistence.size: "5Gi"
    metrics.enabled: "true"
    metrics.serviceMonitor.enabled: "true"
    postgresqlDatabase: "default"
    fullnameOverride: "postgresql"