apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system-helm-repositories
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/flux-system/helm-chart-repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system-github
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/flux-system/github
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
