apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jaeger
  namespace: flux-system
spec:
  interval: 12h
  url: https://jaegertracing.github.io/helm-charts
  timeout: 1m