apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ducknet

resources:
- statefulset.yaml
- service.yaml
- cert.yaml

configMapGenerator:
- name: taskd-config
  namespace: ducknet
  files:
  - config