apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: vpn
  labels:
    app: wireguard
spec:
  type: NodePort
  selector:
    app: wireguard
  ipFamilyPolicy: PreferDualStack
  ports:
  - port: 51820
    targetPort: 51820
    nodePort: 31820
    protocol: UDP