apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persist/service/zigbee2mqtt"
