apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http-prod
  name: duckdotweb
spec:
  rules:
  - host: duck.moe
    http: &http_rules
      paths:
      - path: /
        backend:
          serviceName: duckdotweb
          servicePort: http
  - host: duck.me.uk
    http: *http_rules
  - host: luaduck.co.uk
    http: *http_rules
  tls:
  - hosts:
    - duck.moe
    - duck.me.uk
    - luaduck.co.uk
    secretName: duckdotweb-cert