apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/persist/service/homeassistant"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nagoya