apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: home-assistant
  name: home-assistant
spec:
  endpoints:
  - interval: 60s
    port: http
    path: "/api/prometheus"
    authorization:
      type: "Bearer"
      credentials:
        key: bearertoken
        name: homeassistant
  namespaceSelector:
    matchNames:
    - ln-home
  selector:
    matchLabels:
      app: home-assistant
