apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: ln-data
spec:
  interval: 5m0s
  chart: 
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: nextcloud
      valuesKey: mail-smtp-host
      targetPath: nextcloud.mail.smtp.host
    - kind: Secret
      name: nextcloud
      valuesKey: mail-smtp-port
      targetPath: nextcloud.mail.smtp.port
    - kind: Secret
      name: nextcloud
      valuesKey: mail-smtp-security
      targetPath: nextcloud.mail.smtp.secure
    - kind: Secret
      name: nextcloud
      valuesKey: mail-smtp-authtype
      targetPath: nextcloud.mail.smtp.authtype
    # Fields for SMTP username and password are filled with secret reference inside the chart itself
    # because _that makes sense_
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http-prod
        traefik.ingress.kubernetes.io/preserve-host: "true"
      pathType: ImplementationSpecific
      tls:
        - hosts:
            - files.theleachfamily.me.uk
          secretName: "nextcloud-cert"
    nextcloud:
      host: "files.theleachfamily.me.uk"
      configs:
        reverse-proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_domains' => array(
              'files.theleachfamily.me.uk',
              'files.duck.moe',
              'files.duck.me.uk',
            ),
            'trusted_proxies' => array(
              '172.18.0.0/16',
              'fc00:abc1:0:2::',
            ),
            'overwriteprotocol' => 'https',
          );
      existingSecret:
        enabled: true
        secretName: nextcloud
        usernameKey: admin-user
        passwordKey: admin-pass
        smtpUsernameKey: mail-smtp-user
        smtpPasswordKey: mail-smtp-pass
      mail:
        enabled: true
        fromAddress: "nextcloud"
        domain: "theleachfamily.me.uk"
      # extraVolumes:
      #  - name: hugepages
      #    emptyDir:
      # extraVolumeMounts:
      #      medium: HugePages-2Mi
      #   - name: hugepages
      #     mountPath: /dev/hugepages
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: "postgresql"
      host: "postgresql.ln-database.svc.cluster.local"
      database: "nextcloud"
      existingSecret:
        enabled: true
        secretName: "nextcloud"
        usernameKey: "db-user"
        passwordKey: "db-pass"
    cronjob:
      enabled: true
    persistence:
      enabled: true
      existingClaim: "nextcloud-config"
      nextcloudData:
        enabled: true
        existingClaim: "nextcloud-data"
    rbac:
      enabled: true
    resources:
      requests:
        # hugepages-2Mi: 20Mi
        memory: 100Mi
      limits:
        # limit and request must be the same for hugepages. They are a fixed resource.
        # hugepages-2Mi: 20Mi
        memory: 1Gi
    startupProbe:
      enabled: true
    hpa:
      # Horizontal Pod Autoscaler
      enabled: false
    metrics:
      enabled: true
