---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-oidc
  namespace: argo-cd
spec:
  encryptedData:
    oidc.identiduck.clientSecret: AgCw0jrx26Sx2xTT2mmc84fUKsX6pJzjmXpVYO10Y9XD86lx++gQ1buwPpplgkTncut0Lp5LPY0WtUlg3TkKsKfp4HvyIbBYPhfiBSgxYMR7/qzneWd/4+4sOKVqR844EWcBW/yujCnrQBmil3HIXgASkRrdYCfgah6IV+Rt4AtYU1OR8oDHDzK9DIYAclJ1ZsR4gWih4e5tn7mJkz1RZVyuEoNERwn+1O4qLzgxhYBWC+QFgWhXiqGd4WlD0nf/UQC/FQf/RCNwyJlC18JTNOS6is1SPFoYDyNseVtNWzL11krOhgFPy8oCLhHPURFxfEL+ITOErnKyUgjsJPfXPnyVmOxTPFBZzXOWZaYPXgnWrSx0GoWxlPJU6Unf+c8gZXdE3f08bu8bKlUX0DHn3yC1OqHY1i1+DQAd8itiK7b/ZSBy/9tq1ecidLQOiXAA+pVQy6ZEFqfk9U87Rdu5/7UmXinTOWPKYGldlBNP97r0f6GNDzcxKFbPU3HhVfekAZTnJwuAHAplKZkcv//PMJK6ioI8NLn0PgPQFRIj+SD0Zq2jgYiznhy5lNfrTrXeznANSjkj7vEvx7A19TqJk4GccvX8PqaV9JWpr69ECNTF1su/Evz4BUKE28mJE23VN/2ltr8YHF0+TkFwaw6gcmkmLKavdDltVYhPTkeR6nbhTF+Yw++ICV+DyQYRMhfgTn58PECXpbiN2ve7itKorKO171Qw4u+jOwgqWPSPe5+o0w==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-oidc
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc
      namespace: argo-cd
    type: Opaque
